Repository squarebricks/complete-reference-spring-app, pull requests merged in 2023-03, with the labels that each got.

#9 lot of changes
  pom.xml
  src/main/java/com/orgofarmsgroup/config/AppSecurityConfiguration.java
  src/main/java/com/orgofarmsgroup/dto/error/ErrorDto.java
  src/main/java/com/orgofarmsgroup/exception/UserNotFoundException.java
  src/main/java/com/orgofarmsgroup/exception/handler/RestAPIRootExceptionHandler.java
  src/main/java/com/orgofarmsgroup/interceptor/RestrictionApiInterceptor.java
  src/main/java/com/orgofarmsgroup/interceptor/WebRequestConfig.java
  src/main/java/com/orgofarmsgroup/listener/JpaAuditTrailListener.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-mysql.yml
  src/main/resources/application.yml
  src/test/java/com/orgofarmsgroup/ApplicationTests.java
Labels: enhancement, feature

#10 redis configuration added
  pom.xml
  src/main/java/com/orgofarmsgroup/entity/UserEntity.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-mysql.yml
  src/test/java/com/orgofarmsgroup/controller/graphql/UserGraphQLIntegrationTest.java
  src/test/java/com/orgofarmsgroup/controller/rest/UserIntegrationTest.java
Labels: enhancement, feature

#16 GraphQL file upload functionality added
  pom.xml
  src/main/java/com/orgofarmsgroup/config/AppSecurityConfiguration.java
  src/main/java/com/orgofarmsgroup/config/GraphqlConfiguration.java
  src/main/java/com/orgofarmsgroup/config/GraphqlMultipartHandler.java
  src/main/java/com/orgofarmsgroup/controller/graphql/FileGraphQLController.java
  src/main/java/com/orgofarmsgroup/controller/rest/AdminController.java
  src/main/java/com/orgofarmsgroup/controller/rest/HomeController.java
  src/main/java/com/orgofarmsgroup/dto/misc/FileOperations.java
  src/main/java/com/orgofarmsgroup/entity/AdminEntity.java
  src/main/java/com/orgofarmsgroup/exception/handler/GraphQLAPIRootExceptionHandler.java
  src/main/java/com/orgofarmsgroup/exception/handler/RestAPIRootExceptionHandler.java
  src/main/java/com/orgofarmsgroup/util/MultipartGraphQlRequest.java
  src/main/java/com/orgofarmsgroup/util/MultipartVariableMapper.java
  src/main/java/com/orgofarmsgroup/util/UploadCoercing.java
  src/main/resources/application-local.yml
  src/main/resources/graphql/files.graphqls
  src/main/resources/graphql/roots.graphqls
  src/main/resources/public/index.html
  src/main/resources/templates/error.html
  src/test/java/com/orgofarmsgroup/util/MultipartGraphQlRequestTest.java
  src/test/java/com/orgofarmsgroup/util/MultipartVariableMapperTest.java
  src/test/java/com/orgofarmsgroup/util/UploadCoercingTest.java
Labels: feature

#17 Create .github/workflows/sonarcloud.yml
  .github/workflows/sonarcloud.yml
  pom.xml
  src/main/java/com/orgofarmsgroup/controller/rest/UserController.java
Labels: feature

#19 code smells fixed
  src/main/java/com/orgofarmsgroup/config/GraphqlConfiguration.java
  src/main/java/com/orgofarmsgroup/config/GraphqlMultipartHandler.java
  src/main/java/com/orgofarmsgroup/controller/rest/AdminController.java
  src/main/java/com/orgofarmsgroup/exception/AppException.java
  src/main/java/com/orgofarmsgroup/exception/UserNotFoundException.java
  src/main/java/com/orgofarmsgroup/util/MultipartVariableMapper.java
  src/test/java/com/orgofarmsgroup/util/MultipartVariableMapperTest.java
Labels: bug

#20 code smells
  src/main/java/com/orgofarmsgroup/dto/error/ErrorDto.java
  src/main/java/com/orgofarmsgroup/dto/response/ResponseDto.java
  src/main/java/com/orgofarmsgroup/util/MultipartGraphQlRequest.java
  src/main/resources/public/index.html
  src/main/resources/templates/error.html
  src/test/java/com/orgofarmsgroup/util/MultipartVariableMapperTest.java
Labels: bug

#21 code smells
  .github/workflows/sonarcloud.yml
  src/main/java/com/orgofarmsgroup/util/MultipartGraphQlRequest.java
  src/test/java/com/orgofarmsgroup/util/MultipartVariableMapperTest.java
Labels: bug
